-- ============================================================
-- Seed the 25 AWV (Annual Wellness Visit) worklist rows into
-- hcc_members so the HCC worklist reads all 57 patients from
-- Supabase instead of merging a local mock at load time.
--
-- The AWV mock lives in src/features/awv-worklist/data/mock.js.
-- Each AWV row is mapped to the hcc_members shape here:
--   - visit_type = 'AWV'            (marker for the AWV origin)
--   - pos codes handled at read     (POS_BY_VT maps AWV → Office)
--   - dos_list = [{date, label}]    (the AWV due date acts as DOS)
--   - support_name = assignee       (the AWV outreach owner)
--   - coder/reviewer slots left NULL — AWV isn't a coding row.
--   - RAF fields left NULL — AWV isn't scored.
--   - decile/advillness/frailty/risk_level copied verbatim.
-- Existing HCC rows are untouched; ON CONFLICT DO NOTHING keeps
-- re-runs idempotent.
-- ============================================================

INSERT INTO hcc_members (
  id, member_id, name, initials, gender, age,
  current_visit, total_visits, dos_list, chart_count, doc_status,
  open_icds, create_date, due_label, due_color,
  support_name, support_status,
  coder_name, coder_status,
  reviewer1_name, reviewer1_status,
  reviewer2_name, reviewer2_status,
  reviewer3_name, reviewer3_status,
  rendering_provider, visit_type,
  raf_score, raf_impact, risk_utilization,
  ipa, health_plan, pcp,
  decile, cohort, risk_level, advillness, frailty, language
) VALUES
  ('awv-1',  'M-1000-2500', 'Annette Brave',      'AB', 'M', '67y 3m',  1, 1, '[{"date":"08/15/2026","label":"Due in 5D","labelColor":"var(--status-info)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 5D',   'var(--status-info)',    'A. Beauchamp', 'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Sarah Chen (Family Medicine)',   'AWV', NULL, NULL, false, 'ACP',   'Scan',  'Dr. Roland G.',    '9',  'AWV', 'High',   '3', '2', 'en'),
  ('awv-2',  'M-1200-1300', 'Frank Green',        'FG', 'M', '68y 8m',  1, 1, '[{"date":"07/30/2026","label":"Overdue: 5D","labelColor":"var(--status-error)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Overdue: 5D', 'var(--status-error)',   'M. Thompson',  'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Priya Ramesh (Internal Medicine)','AWV', NULL, NULL, false, 'IPA-1', 'Lab',   'Dr. Sandra K.',    '7',  'AWV', 'Medium', '4', '3', 'en'),
  ('awv-3',  'M-1410-2210', 'Brian Carter',       'BC', 'M', '72y 5m',  1, 1, '[{"date":"09/02/2026","label":"Due in 21D","labelColor":"var(--neutral-200)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 21D',  'var(--neutral-200)',    'L. Torrance',  'Awaiting', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. James Okafor (Family Medicine)',  'AWV', NULL, NULL, false, 'ACP',   'Scan',  'Dr. Ulysses H.',   '10', 'AWV', 'High',   '6', '4', 'en'),
  ('awv-4',  'M-1820-9100', 'David Evans',        'DE', 'M', '75y 1m',  1, 1, '[{"date":"08/10/2026","label":"Due Today","labelColor":"var(--status-warning)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due Today',   'var(--status-warning)', 'E. Johnson',   'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Nadia Rahman (Family Medicine)',  'AWV', NULL, NULL, false, 'IPA-2', 'Lab',   'Dr. Tatum',        '10', 'AWV', 'High',   '5', '5', 'en'),
  ('awv-5',  'M-1136-2748', 'Grace Hill',         'GH', 'F', '70y 10m', 1, 1, '[{"date":"06/30/2026","label":"Completed","labelColor":"var(--status-success)"}]'::jsonb, NULL, '[]'::jsonb, 0, '06/25/2026', 'Completed',   'var(--status-success)', 'O. Twist',     'Completed',   NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Sarah Chen (Family Medicine)',   'AWV', NULL, NULL, false, 'IPA-3', 'X-Ray', 'Dr. Eamon',        '8',  'AWV', 'Medium', '3', '3', 'en'),
  ('awv-6',  'M-1490-3300', 'Cynthia Davis',      'CD', 'F', '65y 2m',  1, 1, '[{"date":"09/12/2026","label":"Due in 30D","labelColor":"var(--neutral-200)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 30D',  'var(--neutral-200)',    'A. Beauchamp', 'Awaiting',    NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Priya Ramesh (Internal Medicine)','AWV', NULL, NULL, false, 'ACP',   'Lab',   'Dr. Reed M.',      '5',  'AWV', 'Low',    '1', '1', 'en'),
  ('awv-7',  'M-1750-4400', 'Emily Foster',       'EF', 'F', '60y 0m',  1, 1, '[{"date":"08/14/2026","label":"Due in 4D","labelColor":"var(--status-info)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 4D',   'var(--status-info)',    'K. Stroman',   'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. James Okafor (Family Medicine)',  'AWV', NULL, NULL, false, 'IPA-1', 'Scan',  'Dr. Tatum',        '6',  'AWV', 'Low',    '2', '1', 'en'),
  ('awv-8',  'M-2000-3200', 'William Jammy',      'WJ', 'M', '60y 10m', 1, 1, '[{"date":"08/20/2026","label":"Due in 10D","labelColor":"var(--status-warning)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 10D',  'var(--status-warning)', 'Oliver Twist', 'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Sarah Chen (Family Medicine)',   'AWV', NULL, NULL, false, 'ACP',   'Lab',   'Dr. Sarah C.',     '9',  'AWV', 'Medium', '4', '2', 'en'),
  ('awv-9',  'M-1510-3430', 'Jessica Clark',      'JC', 'F', '59y 4m',  1, 1, '[{"date":"10/01/2026","label":"Due in 45D","labelColor":"var(--neutral-200)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 45D',  'var(--neutral-200)',    NULL,           'Assign',      NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Nadia Rahman (Family Medicine)',  'AWV', NULL, NULL, false, 'IPA-2', 'Scan',  'Dr. Nancy W.',     '4',  'AWV', 'Low',    '1', '1', 'en'),
  ('awv-10', 'M-1357-3151', 'Richard Scott',      'RS', 'M', '64y 5m',  1, 1, '[{"date":"09/05/2026","label":"Due in 22D","labelColor":"var(--neutral-200)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 22D',  'var(--neutral-200)',    'D. Hintz',     'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Priya Ramesh (Internal Medicine)','AWV', NULL, NULL, false, 'IPA-1', 'Lab',   'Dr. Susan P.',     '6',  'AWV', 'Medium', '2', '2', 'en'),
  ('awv-11', 'M-1340-3120', 'Dorothy Nguyen',     'DN', 'F', '77y 0m',  1, 1, '[{"date":"07/15/2026","label":"Declined","labelColor":"var(--status-error)"}]'::jsonb, NULL, '[]'::jsonb, 0, '07/14/2026', 'Declined',    'var(--status-error)',   'M. Thompson',  'Completed',   NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Sarah Chen (Family Medicine)',   'AWV', NULL, NULL, false, 'ACP',   'Scan',  'Dr. Eamon',        '8',  'AWV', 'High',   '4', '4', 'en'),
  ('awv-12', 'M-1306-3058', 'Patricia Moore',     'PM', 'F', '62y 8m',  1, 1, '[{"date":"08/28/2026","label":"Due in 18D","labelColor":"var(--status-warning)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 18D',  'var(--status-warning)', 'A. Beauchamp', 'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. James Okafor (Family Medicine)',  'AWV', NULL, NULL, false, 'ACP',   'Lab',   'Dr. Reed M.',      '7',  'AWV', 'Medium', '3', '3', 'en'),
  ('awv-13', 'M-1720-4130', 'Charles Rivera',     'CR', 'M', '73y 9m',  1, 1, '[{"date":"08/12/2026","label":"Due in 2D","labelColor":"var(--status-warning)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 2D',   'var(--status-warning)', 'L. Torrance',  'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Nadia Rahman (Family Medicine)',  'AWV', NULL, NULL, false, 'IPA-3', 'X-Ray', 'Dr. Calvin R.',    '8',  'AWV', 'Medium', '4', '3', 'en'),
  ('awv-14', 'M-1442-3306', 'Michelle Jackson',   'MJ', 'F', '61y 5m',  1, 1, '[{"date":"05/05/2026","label":"Completed","labelColor":"var(--status-success)"}]'::jsonb, NULL, '[]'::jsonb, 0, '05/04/2026', 'Completed',   'var(--status-success)', 'E. Johnson',   'Completed',   NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Sarah Chen (Family Medicine)',   'AWV', NULL, NULL, false, 'ACP',   'Lab',   'Dr. Roland G.',    '6',  'AWV', 'Low',    '2', '2', 'en'),
  ('awv-15', 'M-1272-2996', 'Linda Chen',         'LC', 'F', '66y 1m',  1, 1, '[{"date":"09/20/2026","label":"Due in 40D","labelColor":"var(--neutral-200)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 40D',  'var(--neutral-200)',    'D. Hintz',     'Awaiting',    NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Priya Ramesh (Internal Medicine)','AWV', NULL, NULL, false, 'IPA-1', 'Scan',  'Dr. Roland G.',    '9',  'AWV', 'High',   '5', '4', 'en'),
  ('awv-16', 'M-1391-3213', 'Kevin Brown',        'KB', 'M', '58y 11m', 1, 1, '[{"date":"11/05/2026","label":"Due in 80D","labelColor":"var(--neutral-200)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 80D',  'var(--neutral-200)',    NULL,           'Assign',      NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. James Okafor (Family Medicine)',  'AWV', NULL, NULL, false, 'ACP',   'Lab',   'Dr. Nancy W.',     '3',  'AWV', 'Low',    '1', '1', 'en'),
  ('awv-17', 'M-1450-4012', 'Sandra Lee',         'SL', 'F', '68y 3m',  1, 1, '[{"date":"08/11/2026","label":"Due Today","labelColor":"var(--status-warning)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due Today',   'var(--status-warning)', 'L. Torrance',  'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Nadia Rahman (Family Medicine)',  'AWV', NULL, NULL, false, 'IPA-2', 'Scan',  'Dr. Jesse F.',     '9',  'AWV', 'High',   '5', '4', 'en'),
  ('awv-18', 'M-1561-4520', 'James Walker',       'JW', 'M', '78y 2m',  1, 1, '[{"date":"07/25/2026","label":"Overdue: 2w","labelColor":"var(--status-error)"}]'::jsonb, NULL, '[]'::jsonb, 0, '07/24/2026', 'Overdue: 2w', 'var(--status-error)',   'M. Thompson',  'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Sarah Chen (Family Medicine)',   'AWV', NULL, NULL, false, 'IPA-2', 'Scan',  'Dr. Calvin R.',    '10', 'AWV', 'High',   '7', '5', 'en'),
  ('awv-19', 'M-1620-5025', 'Thomas Reed',        'TR', 'M', '74y 6m',  1, 1, '[{"date":"09/10/2026","label":"Due in 30D","labelColor":"var(--neutral-200)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 30D',  'var(--neutral-200)',    'O. Twist',     'Awaiting',    NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Priya Ramesh (Internal Medicine)','AWV', NULL, NULL, false, 'ACP',   'Lab',   'Dr. Jesse F.',     '9',  'AWV', 'High',   '6', '4', 'en'),
  ('awv-20', 'M-1730-5530', 'Anita White',        'AW', 'F', '69y 11m', 1, 1, '[{"date":"08/16/2026","label":"Due in 6D","labelColor":"var(--status-info)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 6D',   'var(--status-info)',    'K. Stroman',   'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Nadia Rahman (Family Medicine)',  'AWV', NULL, NULL, false, 'IPA-3', 'X-Ray', 'Dr. Alan M.',      '7',  'AWV', 'Medium', '3', '3', 'en'),
  ('awv-21', 'M-1820-6210', 'Charles Rivera',     'CR', 'M', '63y 9m',  1, 1, '[{"date":"10/15/2026","label":"Due in 60D","labelColor":"var(--neutral-200)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 60D',  'var(--neutral-200)',    'A. Beauchamp', 'Awaiting',    NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. James Okafor (Family Medicine)',  'AWV', NULL, NULL, false, 'IPA-2', 'Lab',   'Dr. Calvin R.',    '8',  'AWV', 'Medium', '4', '3', 'en'),
  ('awv-22', 'M-1910-6790', 'Sandra Lee',         'SL', 'F', '68y 3m',  1, 1, '[{"date":"08/30/2026","label":"Due in 20D","labelColor":"var(--status-warning)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 20D',  'var(--status-warning)', 'D. Hintz',     'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Sarah Chen (Family Medicine)',   'AWV', NULL, NULL, false, 'IPA-1', 'Scan',  'Dr. Jesse F.',     '9',  'AWV', 'High',   '5', '4', 'en'),
  ('awv-23', 'M-2010-7100', 'Aaron Nguyen',       'AN', 'M', '65y 8m',  1, 1, '[{"date":"09/01/2026","label":"Due in 22D","labelColor":"var(--neutral-200)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 22D',  'var(--neutral-200)',    'L. Torrance',  'Awaiting',    NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Priya Ramesh (Internal Medicine)','AWV', NULL, NULL, false, 'ACP',   'Lab',   'Dr. Alan M.',      '6',  'AWV', 'Medium', '2', '2', 'en'),
  ('awv-24', 'M-2103-7720', 'Maria Hernandez',    'MH', 'F', '71y 4m',  1, 1, '[{"date":"08/13/2026","label":"Due in 3D","labelColor":"var(--status-warning)"}]'::jsonb, NULL, '[]'::jsonb, 0, '08/10/2026', 'Due in 3D',   'var(--status-warning)', 'M. Thompson',  'In Progress', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. Nadia Rahman (Family Medicine)',  'AWV', NULL, NULL, false, 'IPA-1', 'X-Ray', 'Dr. Mallory Hayes','7',  'AWV', 'Medium', '3', '2', 'en'),
  ('awv-25', 'M-2210-8050', 'Paul Thompson',      'PT', 'M', '76y 7m',  1, 1, '[{"date":"04/20/2026","label":"Completed","labelColor":"var(--status-success)"}]'::jsonb, NULL, '[]'::jsonb, 0, '04/19/2026', 'Completed',   'var(--status-success)', 'O. Twist',     'Completed',   NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', NULL, 'Assign', 'Dr. James Okafor (Family Medicine)',  'AWV', NULL, NULL, false, 'ACP',   'Lab',   'Dr. Roland G.',    '8',  'AWV', 'Medium', '4', '3', 'en')
ON CONFLICT (id) DO NOTHING;

-- Verify:
--   SELECT count(*) FROM hcc_members;                 -- expected 57
--   SELECT count(*) FROM hcc_members WHERE visit_type = 'AWV';  -- expected 25
