-- Take EXECUTE away from anon/authenticated on three SECURITY DEFINER functions.
--
-- The linter flags six `*_security_definer_function_executable` warnings across
-- four functions. Only three of them are actually a mistake; the fourth is the
-- deliberate admin door and stays. See the bottom of this file for why.
--
-- WHY THESE THREE ARE WRONG
-- This database has ten SECURITY DEFINER functions. Eight of them are trigger
-- functions and carry the correct ACL — postgres + service_role only:
--
--   handle_new_user, handle_user_first_login, rls_auto_enable,
--   sync_form_response_count, touch_campaigns_updated_by, touch_forms_updated
--
-- Two trigger functions do NOT, and instead sit at the CREATE FUNCTION default
-- of EXECUTE-to-PUBLIC, plus explicit grants to anon and authenticated:
--
--   enforce_profile_authz_fields()   =X/postgres | anon=X | authenticated=X
--   sync_profile_last_sign_in()      =X/postgres | anon=X | authenticated=X
--
-- They are the odd ones out, not a deliberate exception. profiles_guard_authz_fields.sql
-- remembered to lock down the two functions it created by hand
-- (admin_set_user_roles, is_profile_admin) and never revoked the default on the
-- trigger function it created in the same transaction.
--
-- HOW MUCH THIS ACTUALLY MATTERS: less than the WARN suggests. Both return
-- `trigger`, so PostgREST does not expose them on /rest/v1/rpc at all, and a
-- direct call fails with "trigger functions can only be called as triggers"
-- before the body ever runs. This is hygiene — removing a grant that can never
-- be a useful one — not an open door being closed.
--
-- is_profile_admin(uuid) is the one with a real, if small, edge. It IS callable
-- by any signed-in user via /rest/v1/rpc/is_profile_admin, it returns boolean,
-- and it takes an arbitrary uuid. That is an admin-roster oracle: pass the id of
-- every row in `profiles` (readable by all authenticated users under
-- "profiles_read_all_authenticated") and you learn exactly who to target. It
-- does not grant anything, but it is reconnaissance we hand out for free.
--
-- WHY REVOKING IS SAFE
--   • Triggers ignore EXECUTE. Postgres does not check the invoking user's
--     privilege on a trigger function when the trigger fires — it runs as the
--     trigger's owner regardless. profiles_guard_authz_fields keeps working for
--     every signed-in user, and so does the last_sign_in sync.
--   • is_profile_admin has no client caller. `grep -rn is_profile_admin src api
--     scripts` returns nothing, and the app makes exactly one .rpc() call in the
--     whole codebase — admin_set_user_roles. Its only real callers are
--     enforce_profile_authz_fields() and admin_set_user_roles(), both SECURITY
--     DEFINER and owned by postgres, so they reach it through postgres's own
--     grant and never consult the authenticated one.
--   • No RLS policy references it either (checked against pg_policies: zero
--     rows match '%is_profile_admin%'). If a future policy ever calls it, that
--     policy will need `grant execute ... to authenticated` restored — a policy
--     is evaluated as the querying role, so this revoke would break it. Noted
--     here so the next person hits the note before the outage.
--   • service_role keeps EXECUTE throughout, so seeds, api/ and edge functions
--     are untouched.

begin;

-- ── Trigger functions: no role should ever call these directly ──────────────
revoke all on function public.enforce_profile_authz_fields() from public, anon, authenticated;
revoke all on function public.sync_profile_last_sign_in()    from public, anon, authenticated;

-- ── Admin-roster oracle: reachable only through the two definers that use it ─
revoke all on function public.is_profile_admin(uuid) from public, anon, authenticated;

commit;

-- ── Verify ──────────────────────────────────────────────────────────────────
-- All three should show ONLY postgres and service_role:
--   select p.proname, array_to_string(p.proacl::text[], ' | ') as acl
--     from pg_proc p
--    where p.pronamespace = 'public'::regnamespace
--      and p.proname in ('enforce_profile_authz_fields',
--                        'sync_profile_last_sign_in',
--                        'is_profile_admin');
--   Expect: postgres=X/postgres | service_role=X/postgres
--
-- The guard must still fire. As a NON-admin user from the app (not the SQL
-- editor — it has no auth.uid() and is intentionally exempt):
--   update profiles set admin_role = 'Business/Practice Owner' where id = auth.uid();
--   Expect: ERROR 42501 "Only an administrator may change role, ..."
--
-- The admin door must still open. From an admin session in the app, assign a
-- role to somebody else via Settings → Users. Expect success.
--
-- The oracle must be closed. From any signed-in session:
--   await supabase.rpc('is_profile_admin', { uid: '<any-profile-id>' })
--   Expect: 42501 permission denied for function is_profile_admin
--
-- ── Rollback ────────────────────────────────────────────────────────────────
--   grant execute on function public.enforce_profile_authz_fields() to anon, authenticated;
--   grant execute on function public.sync_profile_last_sign_in()    to anon, authenticated;
--   grant execute on function public.is_profile_admin(uuid)         to authenticated;
--
-- ── Deliberately NOT in this file ───────────────────────────────────────────
-- admin_set_user_roles(uuid, text, text, text[]) keeps its EXECUTE grant to
-- authenticated, so its warning will persist and should be treated as accepted.
-- It is the sanctioned door from profiles_guard_authz_fields.sql: the client
-- calls it (SettingsUsers → .rpc('admin_set_user_roles')), and it re-derives the
-- caller's admin status from the database on every call rather than trusting the
-- browser. Revoking it does not make role assignment safer — it removes the only
-- safe path and pushes role writes back onto direct table UPDATEs, which is the
-- privilege-escalation hole that file was written to close.
